#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xDBD2CE893E2D1C87 (cfeck@kde.org)
#
Name     : kbounce
Version  : 18.08.0
Release  : 1
URL      : https://download.kde.org/stable/applications/18.08.0/src/kbounce-18.08.0.tar.xz
Source0  : https://download.kde.org/stable/applications/18.08.0/src/kbounce-18.08.0.tar.xz
Source99 : https://download.kde.org/stable/applications/18.08.0/src/kbounce-18.08.0.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GFDL-1.2 GPL-2.0 LGPL-2.0
Requires: kbounce-bin
Requires: kbounce-data
Requires: kbounce-license
Requires: kbounce-locales
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : libkdegames-dev
BuildRequires : qtbase-dev qtbase-extras mesa-dev

%description
No detailed description available

%package bin
Summary: bin components for the kbounce package.
Group: Binaries
Requires: kbounce-data
Requires: kbounce-license

%description bin
bin components for the kbounce package.


%package data
Summary: data components for the kbounce package.
Group: Data

%description data
data components for the kbounce package.


%package doc
Summary: doc components for the kbounce package.
Group: Documentation

%description doc
doc components for the kbounce package.


%package license
Summary: license components for the kbounce package.
Group: Default

%description license
license components for the kbounce package.


%package locales
Summary: locales components for the kbounce package.
Group: Default

%description locales
locales components for the kbounce package.


%prep
%setup -q -n kbounce-18.08.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1535227436
mkdir clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1535227436
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/kbounce
cp COPYING %{buildroot}/usr/share/doc/kbounce/COPYING
cp COPYING.DOC %{buildroot}/usr/share/doc/kbounce/COPYING.DOC
cp COPYING.LIB %{buildroot}/usr/share/doc/kbounce/COPYING.LIB
pushd clr-build
%make_install
popd
%find_lang kbounce

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/kbounce

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.kde.kbounce.desktop
/usr/share/icons/hicolor/128x128/apps/kbounce.png
/usr/share/icons/hicolor/16x16/apps/kbounce.png
/usr/share/icons/hicolor/22x22/apps/kbounce.png
/usr/share/icons/hicolor/32x32/apps/kbounce.png
/usr/share/icons/hicolor/48x48/apps/kbounce.png
/usr/share/icons/hicolor/64x64/apps/kbounce.png
/usr/share/kbounce/sounds/death.wav
/usr/share/kbounce/sounds/reflect.wav
/usr/share/kbounce/sounds/seconds.wav
/usr/share/kbounce/sounds/timeout.wav
/usr/share/kbounce/sounds/wallend.wav
/usr/share/kbounce/sounds/wallstart.wav
/usr/share/kbounce/themes/default.desktop
/usr/share/kbounce/themes/egyptian_bounce.png
/usr/share/kbounce/themes/egyptian_bounce.svgz
/usr/share/kbounce/themes/geometry.desktop
/usr/share/kbounce/themes/geometry.png
/usr/share/kbounce/themes/kbounce.svg
/usr/share/kbounce/themes/oxygen.desktop
/usr/share/kbounce/themes/oxygen.png
/usr/share/kbounce/themes/oxygen.svgz
/usr/share/kbounce/themes/roads.desktop
/usr/share/kbounce/themes/roads.svgz
/usr/share/kbounce/themes/roads_preview.png
/usr/share/kbounce/themes/the_beach.desktop
/usr/share/kbounce/themes/the_beach.svgz
/usr/share/kbounce/themes/thebeach_preview.png
/usr/share/kxmlgui5/kbounce/kbounceui.rc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/HTML/de/kbounce/button-new.png
/usr/share/doc/HTML/de/kbounce/button-pause.png
/usr/share/doc/HTML/de/kbounce/index.cache.bz2
/usr/share/doc/HTML/de/kbounce/index.docbook
/usr/share/doc/HTML/de/kbounce/kbounce_corridor1.png
/usr/share/doc/HTML/de/kbounce/kbounce_corridor2.png
/usr/share/doc/HTML/de/kbounce/menu-game.png
/usr/share/doc/HTML/de/kbounce/menu-help.png
/usr/share/doc/HTML/de/kbounce/menu-settings.png
/usr/share/doc/HTML/de/kbounce/toolbar.png
/usr/share/doc/HTML/en/kbounce/document-new.png
/usr/share/doc/HTML/en/kbounce/index.cache.bz2
/usr/share/doc/HTML/en/kbounce/index.docbook
/usr/share/doc/HTML/en/kbounce/kbounce_corridor1.png
/usr/share/doc/HTML/en/kbounce/kbounce_corridor2.png
/usr/share/doc/HTML/en/kbounce/media-playback-pause.png
/usr/share/doc/HTML/es/kbounce/index.cache.bz2
/usr/share/doc/HTML/es/kbounce/index.docbook
/usr/share/doc/HTML/et/kbounce/index.cache.bz2
/usr/share/doc/HTML/et/kbounce/index.docbook
/usr/share/doc/HTML/it/kbounce/index.cache.bz2
/usr/share/doc/HTML/it/kbounce/index.docbook
/usr/share/doc/HTML/nl/kbounce/index.cache.bz2
/usr/share/doc/HTML/nl/kbounce/index.docbook
/usr/share/doc/HTML/pt/kbounce/index.cache.bz2
/usr/share/doc/HTML/pt/kbounce/index.docbook
/usr/share/doc/HTML/pt_BR/kbounce/button-new.png
/usr/share/doc/HTML/pt_BR/kbounce/button-pause.png
/usr/share/doc/HTML/pt_BR/kbounce/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kbounce/index.docbook
/usr/share/doc/HTML/pt_BR/kbounce/kbounce_corridor1.png
/usr/share/doc/HTML/pt_BR/kbounce/kbounce_corridor2.png
/usr/share/doc/HTML/pt_BR/kbounce/menu-game.png
/usr/share/doc/HTML/pt_BR/kbounce/menu-settings.png
/usr/share/doc/HTML/pt_BR/kbounce/toolbar.png
/usr/share/doc/HTML/sv/kbounce/index.cache.bz2
/usr/share/doc/HTML/sv/kbounce/index.docbook
/usr/share/doc/HTML/uk/kbounce/index.cache.bz2
/usr/share/doc/HTML/uk/kbounce/index.docbook
/usr/share/doc/HTML/uk/kbounce/kbounce_corridor1.png
/usr/share/doc/HTML/uk/kbounce/kbounce_corridor2.png

%files license
%defattr(-,root,root,-)
/usr/share/doc/kbounce/COPYING
/usr/share/doc/kbounce/COPYING.DOC
/usr/share/doc/kbounce/COPYING.LIB

%files locales -f kbounce.lang
%defattr(-,root,root,-)

